name: CI-CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch: #dispara manuamente
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo codigo
      uses: actions/checkout@v4.2.2
    - name: Autenticação no Docker Hub
      uses: docker/login-action@v3.3.0
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build da imagem Docker
     uses: docker/build-push-action@v6.13.0
     with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          marlonbastida/aula-primeira-pipeline:v${{ github.run_number }}
          marlonbastida/aula-primeira-pipeline:latest
